# Site settings
title: Naren's blog
email: me@narendran.info
description: > # this means to ignore newlines until "baseurl:"
  Just another blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.narendran.info" # the base hostname & protocol for your site
twitter_username: narens
github_username:  narendrans

# Build settings
markdown: kramdown
